#ifndef MACROS_H
#define MACROS_H

#define ARGS_NUM 3
#define READ_AMOUNT 1
// ERRORS
#define ERROR_ARGS_NUM 101
#define ERROR_OPENING_FILE 102
#define ERROR_CANNOT_SORT 103
#define ERROR_GETTING_POS 104
#define ERROR_READING_FILE 105
#define ERROR_WRITING_FILE 106
#define ERROR_GETTING_LENGTH 107

#endif